### ISSUE TITLE
Implement the verify UI

### ISSUE THREAD

**Issue by NguyenVanViet2004** [NguyenVanViet2004/FE-GlowUp#9]
- Verify OTP screen ( Includes both error and completion states when the user enters the OTP code )
- [x] Error state
- [x] Completion state

![Image](https://github.com/user-attachments/assets/e9ffceae-3030-457e-a018-85be458e6c56)

**Comment by KMTus** [comment]
Add Figma UI dark mode for this Issue and other Issue :>
